spring:
    application:
        name: zh-auth
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    redis:
        database: 1
        host: 10.30.50.55
        port: 6379
        pool:
            max-active: 20
#        password: 123456
    datasource:
      name: zh-auth
#      url: jdbc:mysql://${MYSQL_HOST:10.30.50.169}:${MYSQL_PORT:3306}/ag_auth?useUnicode=true&characterEncoding=UTF8
      url: jdbc:mysql://127.0.0.1:3306/zh_auth?useUnicode=true&characterEncoding=UTF8
      username: zhdbuser
      password: zhdbuser123
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    rabbitmq:
#      host: ${RABBIT_MQ_HOST:10.30.50.169}
#      port:  ${RABBIT_MQ_PORT:5672}
      host: 127.0.0.1
      port: 5672
      username: shenyang
      password: shenyang
    zipkin:
        enabled: true
    sleuth:
        sampler:
            percentage: 1
mybatis:
    basepackage: com.navinfo.zhonghuan.auth.mapper
    xmlLocation: classpath:mapper/**/*.xml
    mapper-locations: "classpath*:mapper/*.xml"

server:
    port: 8766 #启动端口

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
#      coreSize: 1000 ##并发执行的最大线程数，默认10
#      maxQueueSize: 1000 ##BlockingQueue的最大队列数
#      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
      coreSize: 1000
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启,记得将IP修改为部署所在服务器的外网IP
        leaseRenewalIntervalInSeconds: 5
        instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
        prefer-ip-address: true
        ip-address: 10.30.50.55
    client:
        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启,记得将IP修改为部署所在服务器的外网IP
            defaultZone: http://${EUREKA_HOST:10.30.50.148}:${EUREKA_PORT:8761}/eureka/

jwt:
  token-header: Authorization
  expire: 3600
  rsa-secret: xx1WET12^%3^(WE45
  user-service: zh-admin

client:
  id: zh-auth
  secret: 123456
  token-header: client-token
  expire: 3600
  rsa-secret: x2318^^(*WRYQWR(QW&T

redis:
  aec-key: xx288&^^%$!@#4dc
  aec-iv: 0123456789abcdef

# 配置swagger
swagger:
    enabled: true
    base-package: com.navinfo.zhonghuan.auth
    title: zh-auth
    version: 1.0.0.SNAPSHOT
    description: 鉴权服务
    contact:
        name: auth

mapper:
  mappers: com.navinfo.zhonghuan.common.mapper.CommonMapper


logging:
  level:
    root: info
    ## 这里设置为info，是因为如果不设置，debug时会不断打印mq日志。
    org.springframework.integration.endpoint.SourcePollingChannelAdapter: info
#    org.springframework.security: DEBUG
