logging:
    level:
#        tk.mybatis: DEBUG
        com.navinfo.zhonghuan.dict: INFO
server:
    port: 8767

spring:
    application:
        name: zh-dict
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: zh-dict
        url: jdbc:mysql://127.0.0.1:3306/zh_dict?useUnicode=true&characterEncoding=UTF8
        username: root
        password: Zhuzhu=567
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        druid:
            filters: stat
            maxActive: 20
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
    redis:
        database: 1
#        host: ${REDIS_HOST:10.30.50.169}
#        port: ${REDIS_PORT:6379}
        host: 127.0.0.1
        port: 6379
        pool:
            max-active: 20
#        password: 123456
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: shenyang
        password: shenyang
    zipkin:
        enabled: true
    sleuth:
        sampler:
            percentage: 1

# 配置数据库
mybatis:
    mapper-locations: "classpath*:mapper/*.xml"

# 配置swagger
swagger:
    enabled: true
    base-package: com.navinfo.zhonghuan.dict
    title: zh-dict
    version: 1.0.0.SNAPSHOT
    description: 数据字典服务
    contact:
        name: dict

# 配置用户认证和服务认证信息
auth:
  serviceId: zh-auth
  user:
    token-header: Authorization
    limit-expire: 1440 # 一天过去,单位分钟
  client:
    id: zh-dict
    secret: 123456
    token-header: client-token

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启,记得将IP修改为部署所在服务器的外网IP
        instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
        prefer-ip-address: true
        ip-address: localhost
    client:
        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启,记得将IP修改为部署所在服务器的外网IP
#            defaultZone: http://${EUREKA_HOST:172.16.1.131}:${EUREKA_PORT:8761}/eureka/
            defaultZone: http://localhost:8761/eureka/

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true



ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


hystrix:
  threadpool:
    default:
            coreSize: 1000
            maxQueueSize: 1000
            queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
